services:
  app:
    image: ghcr.io/hibobmaster/mattermost_bot:latest
    container_name: mattermost_bot
    restart: unless-stopped
    env_file:
      - .env
    # volumes:
      # use env file or config.json
      # - ./config.json:/app/config.json
    networks:
      - mattermost_network

  # pandora:
  #   image: pengzhile/pandora
  #   container_name: pandora
  #   restart: unless-stopped
  #   environment:
  #     - PANDORA_ACCESS_TOKEN=xxxxxxxxxxxxxx
  #     - PANDORA_SERVER=0.0.0.0:8008
  #   networks:
  #     - mattermost_network

networks:
  mattermost_network: